### PR TITLE
fixes #705 - carddex status not working for public collections

### LINKED ISSUE #705: Carddex status not working for public collections
Image

Image

### PR DESCRIPTION
**Pull request by marcelpanse**

### CODE REVIEW

File: frontend/src/types/index.ts [hunk 1]
```diff
@@ -34,6 +34,7 @@ export interface CollectionRow {
   internal_id: number
 
   collection: string[] // array of cardIds
+  collected_card_ids?: string[]
```
Comment (greg19) [inline frontend/src/types/index.ts]: Shouldn't this be one thing?
